/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as splToken from "@solana/spl-token"
import * as beet from "@metaplex-foundation/beet"
import * as web3 from "@solana/web3.js"

/**
 * @category Instructions
 * @category CreateLoyaltyMint
 * @category generated
 */
export type CreateLoyaltyMintInstructionArgs = {
  discountBasisPoints: beet.bignum
  uri: string
  name: string
  symbol: string
}
/**
 * @category Instructions
 * @category CreateLoyaltyMint
 * @category generated
 */
export const createLoyaltyMintStruct = new beet.FixableBeetArgsStruct<
  CreateLoyaltyMintInstructionArgs & {
    instructionDiscriminator: number[] /* size: 8 */
  }
>(
  [
    ["instructionDiscriminator", beet.uniformFixedSizeArray(beet.u8, 8)],
    ["discountBasisPoints", beet.u64],
    ["uri", beet.utf8String],
    ["name", beet.utf8String],
    ["symbol", beet.utf8String],
  ],
  "CreateLoyaltyMintInstructionArgs"
)
/**
 * Accounts required by the _createLoyaltyMint_ instruction
 *
 * @property [_writable_] rewardData
 * @property [_writable_] loyaltyMint
 * @property [_writable_, **signer**] user
 * @property [_writable_] metadata
 * @property [] tokenMetadataProgram
 * @category Instructions
 * @category CreateLoyaltyMint
 * @category generated
 */
export type CreateLoyaltyMintInstructionAccounts = {
  rewardData: web3.PublicKey
  loyaltyMint: web3.PublicKey
  user: web3.PublicKey
  systemProgram?: web3.PublicKey
  rent?: web3.PublicKey
  tokenProgram?: web3.PublicKey
  metadata: web3.PublicKey
  tokenMetadataProgram: web3.PublicKey
}

export const createLoyaltyMintInstructionDiscriminator = [
  29, 100, 89, 61, 239, 34, 129, 31,
]

/**
 * Creates a _CreateLoyaltyMint_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @param args to provide as instruction data to the program
 *
 * @category Instructions
 * @category CreateLoyaltyMint
 * @category generated
 */
export function createCreateLoyaltyMintInstruction(
  accounts: CreateLoyaltyMintInstructionAccounts,
  args: CreateLoyaltyMintInstructionArgs,
  programId = new web3.PublicKey("AbnVVDtVsP6rFUKg5QJjsJZAK9sLfqmjRC5xTVfq4RmD")
) {
  const [data] = createLoyaltyMintStruct.serialize({
    instructionDiscriminator: createLoyaltyMintInstructionDiscriminator,
    ...args,
  })
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.rewardData,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.loyaltyMint,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.user,
      isWritable: true,
      isSigner: true,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.rent ?? web3.SYSVAR_RENT_PUBKEY,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenProgram ?? splToken.TOKEN_PROGRAM_ID,
      isWritable: false,
      isSigner: false,
    },
    {
      pubkey: accounts.metadata,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.tokenMetadataProgram,
      isWritable: false,
      isSigner: false,
    },
  ]

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  })
  return ix
}
